[package]
name = "you_my_sql_db"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "24.0.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.50"
lazy_static = "1.4.0"
